package jp.sji.kansai.android.demo.db;

import jp.sji.kansai.android.demo.db.dao.MHolidayNoDao;
import jp.sji.kansai.android.demo.db.entity.MHolidayNoEntity;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * 勤怠情報DBヘルパークラス
 * @author Hiroshi Tsuji
 *
 */
public class KintaiKanriDBHelper extends SQLiteOpenHelper {

	private Context context = null;

	/** データベース名 */
	private static final String DATABASE_NAME = "KintaiKanri.db";

	/** データベースバージョン */
	private static final int DATABASE_VERSION = 1;

	/**
	 * コンストラクタ
	 * @param context
	 */
	public KintaiKanriDBHelper(Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION);
		this.context = context;
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		// トランザクションテーブルの作成
		createTransactionTable(db);

		// マスタテーブルの作成
		createMasterTable(db);

		// デフォルトマスタデータの登録
//		setDefaultMasterData();

		setDummyData(db);
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
//		db.execSQL("DROP TABLE IF EXISTS " + TABLE_NAME_SERVICE_INFO);
		onCreate(db);
	}

	/**
	 * トランザクションテーブルの作成を行う
	 * @param db
	 */
	private void createTransactionTable(SQLiteDatabase db) {
		// 勤怠情報テーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS T_KINTAI_INFO ( "
				+ "    EMPLOYEE_NO TEXT "
				+ "    ,KINTAI_DATE TEXT "
				+ "    ,SHIFT_NO INTEGER "
				+ "    ,START_TIME TEXT "
				+ "    ,END_TIME TEXT "
				+ "    ,SPECIAL_AFFAIRS TEXT "
				+ "    ,REST_NO INTEGER "
				+ "    ,HOURS_WORKED_SCHEDULED_TIME REAL "
				+ "    ,HOURS_WORKED_OVERTIME_WORK REAL "
				+ "    ,HOURS_WORKED_MIDNIGHT REAL "
				+ "    ,MEMO TEXT "
				+ "    ,LAST_UPDATE_TIME TEXT "
				+ "    ,LAST_UPDATE_USER TEXT "
				+ "    ,DATA_SYNC_KBN INTEGER "
				+ "    ,DATA_DECISION_KBN INTEGER "
				+ "    ,PRIMARY KEY(EMPLOYEE_NO,KINTAI_DATE) "
				+ ") ");

		// 勤怠履歴情報テーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS T_KINTAI_INFO_HISTORY ( "
				+ "    EMPLOYEE_NO TEXT "
				+ "    ,KINTAI_DATE TEXT "
				+ "    ,PROC_DATE TEXT "
				+ "    ,SHIFT_NO INTEGER "
				+ "    ,START_TIME TEXT "
				+ "    ,END_TIME TEXT "
				+ "    ,SPECIAL_AFFAIRS TEXT "
				+ "    ,REST_NO INTEGER "
				+ "    ,HOURS_WORKED_SCHEDULED_TIME REAL "
				+ "    ,HOURS_WORKED_OVERTIME_WORK REAL "
				+ "    ,HOURS_WORKED_MIDNIGHT REAL "
				+ "    ,MEMO TEXT "
				+ "    ,LAST_UPDATE_TIME TEXT "
				+ "    ,LAST_UPDATE_USER TEXT "
				+ "    ,DATA_SYNC_KBN INTEGER "
				+ "    ,DATA_DECISION_KBN INTEGER "
				+ "    ,PRIMARY KEY(EMPLOYEE_NO,KINTAI_DATE,PROC_DATE) "
				+ ") ");

		// プロジェクト情報テーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS T_PROJECT_INFO ( "
				+ "    EMPLOYEE_NO TEXT "
				+ "    ,KINTAI_DATE TEXT "
				+ "    ,PROJECT_NO TEXT "
				+ "    ,WORK_CD TEXT "
				+ "    ,KINTAI_ADMIN_USER TEXT "
				+ "    ,HOURS_WORKED_SCHEDULED_TIME REAL "
				+ "    ,HOURS_WORKED_OVERTIME_WORK REAL "
				+ "    ,HOURS_WORKED_MIDNIGHT REAL "
				+ "    ,LAST_UPDATE_TIME TEXT "
				+ "    ,LAST_UPDATE_USER TEXT "
				+ "    ,DATA_SYNC_KBN INTEGER "
				+ "    ,DATA_DECISION_KBN INTEGER "
				+ "    ,PRIMARY KEY(EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD) "
				+ ") ");

		// プロジェクト履歴情報テーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS T_PROJECT_INFO_HISTORY ( "
				+ "    EMPLOYEE_NO TEXT "
				+ "    ,KINTAI_DATE TEXT "
				+ "    ,PROJECT_NO TEXT "
				+ "    ,WORK_CD TEXT "
				+ "    ,PROC_DATE TEXT "
				+ "    ,KINTAI_ADMIN_USER TEXT "
				+ "    ,HOURS_WORKED_SCHEDULED_TIME REAL "
				+ "    ,HOURS_WORKED_OVERTIME_WORK REAL "
				+ "    ,HOURS_WORKED_MIDNIGHT REAL "
				+ "    ,LAST_UPDATE_TIME TEXT "
				+ "    ,LAST_UPDATE_USER TEXT "
				+ "    ,DATA_SYNC_KBN INTEGER "
				+ "    ,DATA_DECISION_KBN INTEGER "
				+ "    ,PRIMARY KEY(EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,PROC_DATE) "
				+ ") ");
	}

	/**
	 * マスタテーブルの作成を行う
	 * @param db
	 */
	private void createMasterTable(SQLiteDatabase db) {
		// 社員マスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_EMPLOYEE ( "
				+ "    EMPLOYEE_NO TEXT "
				+ "    ,EMPLOYEE_NAME TEXT "
				+ "    ,POST_CD TEXT "
				+ "    ,RANK TEXT "
				+ "    ,PROJECT_CD TEXT "
				+ "    ,WORK_CD TEXT "
				+ "    ,SHIFT_NO INTEGER "
				+ "    ,OVERTIME_WORK_DAYS INTEGER "
				+ "    ,PRIMARY KEY(EMPLOYEE_NO) "
				+ ")");

		// シフトマスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_SHIFT ( "
				+ "    SHIFT_NO INTEGER "
				+ "    ,WORK_START_TIME TEXT "
				+ "    ,WORK_END_TIME TEXT "
				+ "    ,HALF_DAY_OFF_PAUSE TEXT "
				+ "    ,BREAK_1_START_TIME TEXT "
				+ "    ,BREAK_1_END_TIME TEXT "
				+ "    ,BREAK_2_START_TIME TEXT "
				+ "    ,BREAK_2_END_TIME TEXT "
				+ "    ,BREAK_3_START_TIME TEXT "
				+ "    ,BREAK_3_END_TIME TEXT "
				+ "    ,BREAK_4_START_TIME TEXT "
				+ "    ,BREAK_4_END_TIME TEXT "
				+ "    ,BREAK_5_START_TIME TEXT "
				+ "    ,BREAK_5_END_TIME TEXT "
				+ "    ,BREAK_6_START_TIME TEXT "
				+ "    ,BREAK_6_END_TIME TEXT "
				+ "    ,PRIMARY KEY(SHIFT_NO) "
				+ ")");

		// 部署マスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_POST ( "
				+ "    POST_CD TEXT "
				+ "    ,POST_NAME TEXT "
				+ "    ,PRIMARY KEY(POST_CD) "
				+ ")");

		// ランクマスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_RANK ( "
				+ "    RANK TEXT "
				+ "    ,RANK_NAME TEXT "
				+ "    ,PRIMARY KEY(RANK) "
				+ ")");

		// プロジェクトマスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_PROJECT ( "
				+ "    PROJECT_CD TEXT "
				+ "    ,BRANCH_NO TEXT "
				+ "    ,PROJECT_NAME TEXT "
				+ "    ,VALID_PERIOD_START TEXT "
				+ "    ,VALID_PERIOD_END TEXT "
				+ "    ,PRIMARY KEY(PROJECT_CD,BRANCH_NO) "
				+ ")");

		// 作業コードマスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_WORK_CD ( "
				+ "    WORK_CD TEXT "
				+ "    ,WORK_NAME TEXT "
				+ "    ,PRIMARY KEY(WORK_CD) "
				+ ")");

		// カレンダーマスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_CALENDAR ( "
				+ "    YEAR TEXT "
				+ "    ,MONTH TEXT "
				+ "    ,DAY TEXT "
				+ "    ,DAY_OF_WEEK TEXT "
				+ "    ,HOLIDAY_FLG TEXT "
				+ "    ,PRIMARY KEY(YEAR,MONTH,DAY,DAY_OF_WEEK,HOLIDAY_FLG) "
				+ ")");

		// 休暇番号マスタテーブルを作成する
		db.execSQL("CREATE TABLE IF NOT EXISTS M_HOLIDAY_NO ( "
				+ "    HOLIDAY_NO TEXT "
				+ "    ,HOLIDAY_NAME TEXT "
				+ "    ,PRIMARY KEY(HOLIDAY_NO) "
				+ ")");
	}

	// TODO [Tsuji] メソッド自体の要・不要含めて検討
	private void setDefaultMasterData(SQLiteDatabase db) {
		// ------------------------------
		// 休暇番号マスタ
		// ------------------------------
		MHolidayNoDao holidayNoDao = new MHolidayNoDao(this.context);
		MHolidayNoEntity holidayNoEntity = new MHolidayNoEntity();

		MHolidayNoEntity holidayNoResultEntity = holidayNoDao.selectPK("1");
		if (holidayNoResultEntity == null) {
			holidayNoEntity.setHolidayNo("1");
			holidayNoEntity.setHolidayNo("全休");
			holidayNoDao.insert(holidayNoEntity);
		}

		holidayNoResultEntity = holidayNoDao.selectPK("2");
		if (holidayNoResultEntity == null) {
			holidayNoEntity.setHolidayNo("2");
			holidayNoEntity.setHolidayNo("午前休");
			holidayNoDao.insert(holidayNoEntity);
		}

		holidayNoResultEntity = holidayNoDao.selectPK("3");
		if (holidayNoResultEntity == null) {
			holidayNoEntity.setHolidayNo("3");
			holidayNoEntity.setHolidayNo("午後休");
			holidayNoDao.insert(holidayNoEntity);
		}
	}

	// TODO [Tsuji] ダミーデータ投入用に作成　後で消す
	private void setDummyData(SQLiteDatabase db) {
		// 勤怠情報ダミーデータ登録
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111201','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111202','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111203','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111204','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111205','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111206','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111207','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111208','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111209','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111210','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111211','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111212','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111213','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111214','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111215','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111216','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111217','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111218','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111219','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111220','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111221','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111222','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111223','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111224','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111225','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111226','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111227','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111228','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111229','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111230','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111231','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120104','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120105','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120106','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120107','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120108','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120109','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120110','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120111','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120112','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120113','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120114','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120115','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120116','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120117','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120118','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120119','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120120','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120121','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120122','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120123','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120124','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120125','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120126','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120127','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120128','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120129','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120130','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120131','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120201','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120202','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120203','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120204','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120205','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120206','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120207','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120208','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120209','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120210','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120211','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120212','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120213','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120214','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120215','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120216','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120217','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120218','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120219','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120220','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120221','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120222','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120223','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120224','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120225','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120226','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120227','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120228','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");
		db.execSQL("INSERT INTO T_KINTAI_INFO (EMPLOYEE_NO,KINTAI_DATE,SHIFT_NO,START_TIME,END_TIME,SPECIAL_AFFAIRS,REST_NO,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,MEMO,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120229','1','0900','1745','特記事項','','','','','メモ','0','0','0','0');");

		// プロジェクト情報ダミーデータ登録
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111201','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111202','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111203','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111204','3V-99999999-009','L','00839','6','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111204','3V-99999999-009','Z0100','00839','1.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111205','3V-99999999-009','Z9000','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111206','3V-99999999-009','L','00839','7.75','3.5','1','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111207','3V-99999999-009','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111208','3V-99999999-009','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111209','3V-99999999-009','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111210','3V-99999999-009','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111211','3V-99999999-009','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111212','3V-99999999-009','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111213','3V-99999999-009','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111214','3V-99999999-009','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111215','3V-99999999-009','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111216','3V-99999999-009','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111217','3V-99999999-009','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111218','3V-99999999-009','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111219','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111220','3V-99999999-009','L','00839','7.75','3.5','2','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111221','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111222','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111223','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111224','3V-99999999-009','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111225','3V-99999999-009','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111226','3V-99999999-009','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111227','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111228','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111229','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111230','3V-99999999-009','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20111231','3V-99999999-009','L','00839','7.75','3.5','3','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120104','3V-99999999-010','L','00839','6','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120104','3V-99999999-010','Z0100','00839','1.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120105','3V-99999999-010','Z9000','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120106','3V-99999999-010','L','00839','7.75','3.5','1','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120107','3V-99999999-010','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120108','3V-99999999-010','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120109','3V-99999999-010','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120110','3V-99999999-010','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120111','3V-99999999-010','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120112','3V-99999999-010','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120113','3V-99999999-010','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120114','3V-99999999-010','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120115','3V-99999999-010','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120116','3V-99999999-010','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120117','3V-99999999-010','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120118','3V-99999999-010','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120119','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120120','3V-99999999-010','L','00839','7.75','3.5','2','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120121','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120122','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120123','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120124','3V-99999999-010','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120125','3V-99999999-010','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120126','3V-99999999-010','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120127','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120128','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120129','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120130','3V-99999999-010','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120131','3V-99999999-010','L','00839','7.75','3.5','3','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120201','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120202','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120203','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120204','3V-99999999-011','Z0100','00839','1.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120205','3V-99999999-011','Z9000','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120206','3V-99999999-011','L','00839','7.75','3.5','1','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120207','3V-99999999-011','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120208','3V-99999999-011','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120209','3V-99999999-011','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120210','3V-99999999-011','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120211','3V-99999999-011','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120212','3V-99999999-011','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120213','3V-99999999-011','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120214','3V-99999999-011','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120215','3V-99999999-011','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120216','3V-99999999-011','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120217','3V-99999999-011','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120218','3V-99999999-011','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120219','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120220','3V-99999999-011','L','00839','7.75','3.5','2','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120221','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120222','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120223','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120224','3V-99999999-011','L','00839','7.75','1','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120225','3V-99999999-011','L','00839','7.75','2','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120226','3V-99999999-011','L','00839','7.75','3','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120227','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120228','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
		db.execSQL("INSERT INTO T_PROJECT_INFO (EMPLOYEE_NO,KINTAI_DATE,PROJECT_NO,WORK_CD,KINTAI_ADMIN_USER,HOURS_WORKED_SCHEDULED_TIME,HOURS_WORKED_OVERTIME_WORK,HOURS_WORKED_MIDNIGHT,LAST_UPDATE_TIME,LAST_UPDATE_USER,DATA_SYNC_KBN,DATA_DECISION_KBN) VALUES ('99999','20120229','3V-99999999-011','L','00839','7.75','0','0','0','0','0','0');");
	}
}
